//! axum-based WebSocket server.
//!
//! Each connection gets a dedicated task that multiplexes incoming client
//! requests with outgoing broadcast events. A lagged broadcast receiver
//! triggers a `state_reset` event with the full task list.
//!
//! Authentication is required for WebSocket connections. Clients must provide
//! a bearer token via the `Authorization` header or `?token=` query param.
//! A separate `POST /pair` endpoint is available without authentication to
//! exchange a pairing code for a bearer token.

use std::collections::HashMap;
use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::{Arc, Mutex};

use axum::body::Body;
use axum::extract::ws::{Message, WebSocket, WebSocketUpgrade};
use axum::extract::{Query, State};
use axum::http::{HeaderMap, StatusCode};
use axum::response::{IntoResponse, Response};
use axum::routing::{get, post};
use axum::{Json, Router};
use rusqlite::Connection;
use serde::{Deserialize, Serialize};
use subtle::ConstantTimeEq;
use tokio::sync::broadcast;

use orkestra_core::workflow::WorkflowApi;

use crate::diff_cache::DiffCacheState;
use crate::highlight::SyntaxHighlighter;
use crate::interactions::auth::{pair_device, verify_token};
use crate::interactions::command::dispatch::{self, CommandContext};
use crate::types::{AuthError, ErrorResponse, Event, Request, Response as WsResponse};

// ============================================================================
// Server State
// ============================================================================

/// Shared server state injected into each axum handler.
#[derive(Clone)]
struct ServerState {
    ctx: Arc<CommandContext>,
    event_tx: broadcast::Sender<Event>,
    /// Static development token. If set, connections using this token bypass DB auth.
    static_token: Option<String>,
}

// ============================================================================
// Public API
// ============================================================================

/// Start the WebSocket server on `bind_addr`.
///
/// Requires a bearer token on the WebSocket upgrade path. The `static_token`
/// parameter enables a fixed development token that bypasses device pairing.
/// Pass `None` in production to require the full pairing flow.
///
/// This is an async future — `await` it to run the server until it stops.
pub async fn start(
    api: Arc<Mutex<WorkflowApi>>,
    event_tx: broadcast::Sender<Event>,
    conn: Arc<Mutex<Connection>>,
    static_token: Option<String>,
    bind_addr: SocketAddr,
    project_root: PathBuf,
) -> Result<(), std::io::Error> {
    let ctx = Arc::new(CommandContext {
        api,
        project_root: Arc::new(project_root),
        highlighter: Arc::new(SyntaxHighlighter::new()),
        diff_cache: Arc::new(DiffCacheState::new()),
        conn,
    });

    let state = ServerState {
        ctx,
        event_tx,
        static_token,
    };

    let router = Router::new()
        .route("/ws", get(ws_handler))
        .route("/pair", post(pair_handler))
        .with_state(state);

    let listener = tokio::net::TcpListener::bind(bind_addr).await?;

    tracing::info!("WebSocket server listening on {bind_addr}");

    axum::serve(listener, router).await
}

// ============================================================================
// WebSocket Upgrade
// ============================================================================

/// HTTP handler that upgrades the connection to WebSocket after checking auth.
async fn ws_handler(
    upgrade: WebSocketUpgrade,
    headers: HeaderMap,
    Query(query): Query<HashMap<String, String>>,
    State(state): State<ServerState>,
) -> Response {
    let token = extract_bearer_token(&headers).or_else(|| query.get("token").cloned());

    match token {
        Some(t) if is_authenticated(&state, &t).await => upgrade
            .on_upgrade(move |socket| handle_connection(socket, state))
            .into_response(),
        _ => StatusCode::UNAUTHORIZED.into_response(),
    }
}

// ============================================================================
// Pairing Endpoint
// ============================================================================

/// Request body for `POST /pair`.
#[derive(Debug, Deserialize)]
struct PairRequest {
    code: String,
    device_name: String,
}

/// Response body for `POST /pair`.
#[derive(Debug, Serialize)]
struct PairResponse {
    token: String,
}

/// `POST /pair` — exchange a pairing code for a bearer token.
///
/// This endpoint is intentionally unauthenticated: it's how clients obtain
/// their first token. The pairing code is generated by the daemon and must
/// be entered within 5 minutes.
async fn pair_handler(
    State(state): State<ServerState>,
    Json(body): Json<PairRequest>,
) -> Response<Body> {
    let conn = Arc::clone(&state.ctx.conn);
    let code = body.code;
    let device_name = body.device_name;

    let result =
        tokio::task::spawn_blocking(move || pair_device::execute(&conn, &code, &device_name)).await;

    match result {
        Ok(Ok(token)) => Json(PairResponse { token }).into_response(),
        Ok(Err(AuthError::InvalidCode)) => {
            let body =
                serde_json::json!({"error": "Invalid, expired, or already claimed pairing code"});
            (StatusCode::BAD_REQUEST, Json(body)).into_response()
        }
        Ok(Err(e)) => {
            let body = serde_json::json!({"error": e.to_string()});
            (StatusCode::INTERNAL_SERVER_ERROR, Json(body)).into_response()
        }
        Err(e) => {
            let body = serde_json::json!({"error": e.to_string()});
            (StatusCode::INTERNAL_SERVER_ERROR, Json(body)).into_response()
        }
    }
}

// ============================================================================
// Connection Handler
// ============================================================================

/// Drive a single WebSocket connection.
///
/// Runs a `select!` loop that handles:
/// - Client messages → dispatch → send response
/// - Broadcast events → serialize → send to client
/// - Lagged broadcast → send `state_reset` with full task snapshot
async fn handle_connection(mut socket: WebSocket, state: ServerState) {
    let mut event_rx = state.event_tx.subscribe();

    loop {
        tokio::select! {
            // Incoming client message
            msg = socket.recv() => {
                match msg {
                    Some(Ok(Message::Text(text))) => {
                        let response = handle_text_message(
                            &text,
                            Arc::clone(&state.ctx),
                            state.event_tx.clone(),
                        )
                        .await;
                        let serialized = serde_json::to_string(&response)
                            .unwrap_or_else(|_| r#"{"error":"serialization failed"}"#.into());
                        if socket.send(Message::Text(serialized.into())).await.is_err() {
                            break;
                        }
                    }
                    Some(Ok(Message::Close(_)) | Err(_)) | None => break,
                    Some(Ok(_)) => {} // ignore binary / ping / pong
                }
            }

            // Outgoing broadcast event
            broadcast_result = event_rx.recv() => {
                match broadcast_result {
                    Ok(event) => {
                        let serialized = serde_json::to_string(&event)
                            .unwrap_or_else(|_| r#"{"event":"error","data":{}}"#.into());
                        if socket.send(Message::Text(serialized.into())).await.is_err() {
                            break;
                        }
                    }
                    Err(broadcast::error::RecvError::Lagged(_)) => {
                        // Client missed messages — send a full state reset.
                        if let Some(reset_event) = build_state_reset(&state.ctx).await {
                            let serialized = serde_json::to_string(&reset_event)
                                .unwrap_or_else(|_| r#"{"event":"state_reset","data":{}}"#.into());
                            if socket.send(Message::Text(serialized.into())).await.is_err() {
                                break;
                            }
                        }
                    }
                    Err(broadcast::error::RecvError::Closed) => break,
                }
            }
        }
    }
}

// ============================================================================
// Helpers
// ============================================================================

/// Check whether a token is valid for this server.
///
/// Accepts either the static development token (constant-time comparison) or
/// a token verified against the `device_tokens` table via `spawn_blocking`.
async fn is_authenticated(state: &ServerState, token: &str) -> bool {
    // Constant-time comparison for static token to prevent timing attacks.
    if let Some(static_token) = &state.static_token {
        if token.as_bytes().ct_eq(static_token.as_bytes()).into() {
            return true;
        }
    }

    let conn = Arc::clone(&state.ctx.conn);
    let token = token.to_string();
    match tokio::task::spawn_blocking(move || verify_token::execute(&conn, &token)).await {
        Ok(Ok(_)) => true,
        Ok(Err(e)) => {
            tracing::warn!("Token verification failed: {e}");
            false
        }
        Err(e) => {
            tracing::error!("Token verification panicked: {e}");
            false
        }
    }
}

/// Extract the bearer token from an `Authorization: Bearer <token>` header.
fn extract_bearer_token(headers: &HeaderMap) -> Option<String> {
    let auth = headers.get("Authorization")?.to_str().ok()?;
    auth.strip_prefix("Bearer ").map(|t| t.trim().to_string())
}

/// Parse a text message and dispatch it to the appropriate handler.
///
/// Returns a JSON-serializable envelope (either a `WsResponse` or `ErrorResponse`).
async fn handle_text_message(
    text: &str,
    ctx: Arc<CommandContext>,
    event_tx: broadcast::Sender<Event>,
) -> serde_json::Value {
    let request: Request = match serde_json::from_str(text) {
        Ok(r) => r,
        Err(e) => {
            return serde_json::to_value(ErrorResponse {
                id: String::new(),
                error: crate::types::ErrorPayload::invalid_params(e.to_string()),
            })
            .unwrap_or(serde_json::Value::Null);
        }
    };

    let id = request.id.clone();

    match dispatch::execute(&request.method, ctx, event_tx, request.params).await {
        Ok(result) => {
            serde_json::to_value(WsResponse { id, result }).unwrap_or(serde_json::Value::Null)
        }
        Err(error) => {
            serde_json::to_value(ErrorResponse { id, error }).unwrap_or(serde_json::Value::Null)
        }
    }
}

/// Build a `state_reset` event containing all active task views.
async fn build_state_reset(ctx: &Arc<CommandContext>) -> Option<Event> {
    let api = Arc::clone(&ctx.api);
    match tokio::task::spawn_blocking(move || {
        let api = api.lock().map_err(|e| format!("Lock poisoned: {e}"))?;
        let tasks = api
            .list_task_views()
            .map_err(|e| format!("DB query failed: {e}"))?;
        Ok::<_, String>(Event::new(
            "state_reset",
            serde_json::to_value(tasks).unwrap_or(serde_json::Value::Array(vec![])),
        ))
    })
    .await
    {
        Ok(Ok(event)) => Some(event),
        Ok(Err(reason)) => {
            tracing::error!("Failed to build state reset: {reason}");
            None
        }
        Err(e) => {
            tracing::error!("State reset task panicked: {e}");
            None
        }
    }
}
