//! Wire protocol types shared between the relay server and relay clients.

use serde::{Deserialize, Serialize};

/// Canonical wire format for all messages exchanged over the relay WebSocket.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum RelayMessage {
    /// Sent by both daemons and clients immediately after connecting.
    Register {
        device_id: String,
        role: Role,
        #[serde(skip_serializing_if = "Option::is_none")]
        token: Option<String>,
    },
    /// Request (client→relay→daemon) or response (daemon→relay→client).
    Forward {
        /// Set by the relay when forwarding client→daemon; omitted by the client.
        #[serde(skip_serializing_if = "Option::is_none")]
        client_id: Option<String>,
        /// Unique request identifier generated by the relay; echoed by the daemon in its response.
        #[serde(skip_serializing_if = "Option::is_none")]
        request_id: Option<String>,
        /// Bearer token; set by relay when forwarding client→daemon.
        #[serde(skip_serializing_if = "Option::is_none")]
        token: Option<String>,
        payload: serde_json::Value,
    },
    /// Push notification from daemon to all connected clients for a device.
    Event { payload: serde_json::Value },
    /// Structured error sent by the relay to the affected party.
    Error { code: String, message: String },
}

impl RelayMessage {
    /// Convenience constructor for error messages.
    pub fn error(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self::Error {
            code: code.into(),
            message: message.into(),
        }
    }
}

/// Role a connecting peer assumes on registration.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "snake_case")]
pub enum Role {
    Daemon,
    Client,
}
